backend:
    image: oceanbarrier/findadogforme-backend
    script:
    - cd backend
    - echo $DATABASE_CONFIG | base64 -d > config.py
    - python3 tests.py
    - cd ..

frontend:
    image: oceanbarrier/findadogforme-frontend
    script:
    - cd frontend
    - mocha --reporter spec --no-timeouts test/mocha_test_babel.js
