backend:
    image: oceanbarrier/findadogforme-backend
    script:
    - cd backend
    - echo $DATABASE_CONFIG | base64 -d > config.py
    - python3 tests.py
    - cd ..

frontend and postman:
    image: oceanbarrier/findadogforme-frontend
    script:
    - cd frontend
    - mocha --reporter spec --no-timeouts test/mocha_test.js
    - cd ..
    - newman run Postman.json
