FROM python:3

RUN apt-get update

RUN apt-get -y install libboost-all-dev
RUN apt-get -y install libgmp-dev
RUN apt-get -y install vim

RUN pip install --upgrade pip
RUN pip --version

RUN pip install alembic
RUN pip install appdirs
RUN pip install attrs
RUN pip install black
RUN pip install certifi
RUN pip install chardet
RUN pip install Click
RUN pip install Flask
RUN pip install Flask-Cors
RUN pip install Flask-Migrate
RUN pip install Flask-Restless
RUN pip install Flask-Script
RUN pip install Flask-SQLAlchemy
RUN pip install idna
RUN pip install itsdangerous
RUN pip install Jinja2
RUN pip install Mako
RUN pip install MarkupSafe
RUN pip install mimerender
RUN pip install pprint
RUN pip install psycopg2
RUN pip install python-dateutil
RUN pip install python-dotenv
RUN pip install python-editor
RUN pip install python-mimeparse
RUN pip install requests
RUN pip install six
RUN pip install SQLAlchemy
RUN pip install toml
RUN pip install urllib3
RUN pip install Werkzeug

CMD bash
