seed:
	python3 activity_seeding.py
	python3 pets_seeding.py
	python3 shelter_seeding.py
	python3 breeds_seeding.py

re_seed:
	python3 activity_seeding.py
	python3 pets_seeding.py
	python3 shelter_seeding.py

schema_update:
	python3 manage.py db migrate
	python3 manage.py db upgrade
