const VALID_CITIES = [
  {value: "Adkins", label: "Adkins"},
  {value: "Aledo", label: "Aledo"},
  {value: "Alvin", label: "Alvin"},
  {value: "Angleton", label: "Angleton"},
  {value: "Arlington", label: "Arlington"},
  {value: "Austin", label: "Austin"},
  {value: "Bandera", label: "Bandera"},
  {value: "Bastrop", label: "Bastrop"},
  {value: "Baytown", label: "Baytown"},
  {value: "Beeville", label: "Beeville"},
  {value: "Bellaire", label: "Bellaire"},
  {value: "Benbrook", label: "Benbrook"},
  {value: "Bergheim", label: "Bergheim"},
  {value: "Bertram", label: "Bertram"},
  {value: "Blanco", label: "Blanco"},
  {value: "Blessing", label: "Blessing"},
  {value: "Boerne", label: "Boerne"},
  {value: "Brenham", label: "Brenham"},
  {value: "Brownwood", label: "Brownwood"},
  {value: "Bryan", label: "Bryan"},
  {value: "Buchanan Dam", label: "Buchanan Dam"},
  {value: "Buda", label: "Buda"},
  {value: "Buffalo", label: "Buffalo"},
  {value: "Bulverde", label: "Bulverde"},
  {value: "Burleson", label: "Burleson"},
  {value: "Canyon Lake", label: "Canyon Lake"},
  {value: "Cat Spring", label: "Cat Spring"},
  {value: "Cedar Creek", label: "Cedar Creek"},
  {value: "Cedar Hill", label: "Cedar Hill"},
  {value: "Cedar Park", label: "Cedar Park"},
  {value: "Cleveland", label: "Cleveland"},
  {value: "Clifton", label: "Clifton"},
  {value: "Coldspring", label: "Coldspring"},
  {value: "Coleman", label: "Coleman"},
  {value: "College Station", label: "College Station"},
  {value: "Comanche", label: "Comanche"},
  {value: "Comfort", label: "Comfort"},
  {value: "Conroe", label: "Conroe"},
  {value: "Converse", label: "Converse"},
  {value: "Copperas Cove", label: "Copperas Cove"},
  {value: "Corpus Christi", label: "Corpus Christi"},
  {value: "Corsicana", label: "Corsicana"},
  {value: "Covington", label: "Covington"},
  {value: "Crowley", label: "Crowley"},
  {value: "Cuero", label: "Cuero"},
  {value: "Cypress", label: "Cypress"},
  {value: "Dallas", label: "Dallas"},
  {value: "Dickinson", label: "Dickinson"},
  {value: "Dripping Springs", label: "Dripping Springs"},
  {value: "Duncanville", label: "Duncanville"},
  {value: "Edna", label: "Edna"},
  {value: "El Campo", label: "El Campo"},
  {value: "Elgin", label: "Elgin"},
  {value: "Everman", label: "Everman"},
  {value: "Fischer", label: "Fischer"},
  {value: "Floresville", label: "Floresville"},
  {value: "Fort Worth", label: "Fort Worth"},
  {value: "Fredericksburg", label: "Fredericksburg"},
  {value: "Friendswood", label: "Friendswood"},
  {value: "Fulshear", label: "Fulshear"},
  {value: "Fulton", label: "Fulton"},
  {value: "Georgetown", label: "Georgetown"},
  {value: "Godley", label: "Godley"},
  {value: "Goliad", label: "Goliad"},
  {value: "Gonzales", label: "Gonzales"},
  {value: "Granbury", label: "Granbury"},
  {value: "Grand Prairie", label: "Grand Prairie"},
  {value: "Gun Barrel City", label: "Gun Barrel City"},
  {value: "Hearne", label: "Hearne"},
  {value: "Helotes", label: "Helotes"},
  {value: "Hempstead", label: "Hempstead"},
  {value: "Highlands", label: "Highlands"},
  {value: "Hillsboro", label: "Hillsboro"},
  {value: "Hitchcock", label: "Hitchcock"},
  {value: "Horseshoe Bay", label: "Horseshoe Bay"},
  {value: "Houston", label: "Houston"},
  {value: "Humble", label: "Humble"},
  {value: "Industry", label: "Industry"},
  {value: "Jarrell", label: "Jarrell"},
  {value: "Junction", label: "Junction"},
  {value: "Katy", label: "Katy"},
  {value: "Kendalia", label: "Kendalia"},
  {value: "Kenedy", label: "Kenedy"},
  {value: "Kennedale", label: "Kennedale"},
  {value: "Kerrville", label: "Kerrville"},
  {value: "Killeen", label: "Killeen"},
  {value: "Kingwood", label: "Kingwood"},
  {value: "Kyle", label: "Kyle"},
  {value: "La Vernia", label: "La Vernia"},
  {value: "Lago Vista", label: "Lago Vista"},
  {value: "Lake Jackson", label: "Lake Jackson"},
  {value: "Lakeway", label: "Lakeway"},
  {value: "Lampasas", label: "Lampasas"},
  {value: "Lancaster", label: "Lancaster"},
  {value: "League City", label: "League City"},
  {value: "Leander", label: "Leander"},
  {value: "Liberty Hill", label: "Liberty Hill"},
  {value: "Liverpool", label: "Liverpool"},
  {value: "Livingston", label: "Livingston"},
  {value: "Lockhart", label: "Lockhart"},
  {value: "Lott", label: "Lott"},
  {value: "Luling", label: "Luling"},
  {value: "Lytle", label: "Lytle"},
  {value: "Mabank", label: "Mabank"},
  {value: "Madisonville", label: "Madisonville"},
  {value: "Magnolia", label: "Magnolia"},
  {value: "Malakoff", label: "Malakoff"},
  {value: "Manchaca", label: "Manchaca"},
  {value: "Mansfield", label: "Mansfield"},
  {value: "Manvel", label: "Manvel"},
  {value: "Marble Falls", label: "Marble Falls"},
  {value: "Mason", label: "Mason"},
  {value: "Mexia", label: "Mexia"},
  {value: "Midlothian", label: "Midlothian"},
  {value: "Mingus", label: "Mingus"},
  {value: "Missouri City", label: "Missouri City"},
  {value: "Montgomery", label: "Montgomery"},
  {value: "Nassau Bay", label: "Nassau Bay"},
  {value: "Navasota", label: "Navasota"},
  {value: "New Braunfels", label: "New Braunfels"},
  {value: "Nixon", label: "Nixon"},
  {value: "Ovilla", label: "Ovilla"},
  {value: "Palacios", label: "Palacios"},
  {value: "Palestine", label: "Palestine"},
  {value: "Pasadena", label: "Pasadena"},
  {value: "Pearland", label: "Pearland"},
  {value: "Pearsall", label: "Pearsall"},
  {value: "Pflugerville", label: "Pflugerville"},
  {value: "Pipe Creek", label: "Pipe Creek"},
  {value: "Pleasanton", label: "Pleasanton"},
  {value: "Porter", label: "Porter"},
  {value: "Poteet", label: "Poteet"},
  {value: "Red Oak", label: "Red Oak"},
  {value: "Richmond", label: "Richmond"},
  {value: "Rockdale", label: "Rockdale"},
  {value: "Rosenberg", label: "Rosenberg"},
  {value: "Rosharon", label: "Rosharon"},
  {value: "Round Rock", label: "Round Rock"},
  {value: "San Antonio", label: "San Antonio"},
  {value: "San Leon", label: "San Leon"},
  {value: "San Marcos", label: "San Marcos"},
  {value: "Santa Fe", label: "Santa Fe"},
  {value: "Schertz", label: "Schertz"},
  {value: "Scurry", label: "Scurry"},
  {value: "Seabrook", label: "Seabrook"},
  {value: "Sealy", label: "Sealy"},
  {value: "Seguin", label: "Seguin"},
  {value: "Seven Points", label: "Seven Points"},
  {value: "Sheridan", label: "Sheridan"},
  {value: "Smithville", label: "Smithville"},
  {value: "Somerville", label: "Somerville"},
  {value: "South Houston ", label: "South Houston "},
  {value: "Spring", label: "Spring"},
  {value: "Stafford", label: "Stafford"},
  {value: "Stephenville", label: "Stephenville"},
  {value: "Sugar Land", label: "Sugar Land"},
  {value: "Taylor", label: "Taylor"},
  {value: "Temple", label: "Temple"},
  {value: "The Woodlands", label: "The Woodlands"},
  {value: "Thorndale", label: "Thorndale"},
  {value: "Tomball", label: "Tomball"},
  {value: "Universal City", label: "Universal City"},
  {value: "Uvalde", label: "Uvalde"},
  {value: "Van Vleck", label: "Van Vleck"},
  {value: "Venus", label: "Venus"},
  {value: "Victoria", label: "Victoria"},
  {value: "Von Ormy", label: "Von Ormy"},
  {value: "Waco", label: "Waco"},
  {value: "Waller", label: "Waller"},
  {value: "Wallis", label: "Wallis"},
  {value: "Waxahachie", label: "Waxahachie"},
  {value: "Weatherford", label: "Weatherford"},
  {value: "Webster", label: "Webster"},
  {value: "Wharton", label: "Wharton"},
  {value: "White Settlement", label: "White Settlement"},
  {value: "Whitney", label: "Whitney"},
  {value: "Wimberley", label: "Wimberley"},
  {value: "Windcrest", label: "Windcrest"},
];
export { VALID_CITIES };

const VALID_BREEDS = [
  {value: "norfolk terrier", label: "norfolk terrier"},
  {value: "doberman pinscher", label: "doberman pinscher"},
  {value: "boxer", label: "boxer"},
  {value: "pug", label: "pug"},
  {value: "bichon frise", label: "bichon frise"},
  {value: "bull terrier", label: "bull terrier"},
  {value: "briard", label: "briard"},
  {value: "beagle", label: "beagle"},
  {value: "tibetan mastiff", label: "tibetan mastiff"},
  {value: "shih tzu", label: "shih tzu"},
  {value: "field spaniel", label: "field spaniel"},
  {value: "keeshond", label: "keeshond"},
  {value: "english springer spaniel", label: "english springer spaniel"},
  {value: "staffordshire bull terrier", label: "staffordshire bull terrier"},
  {value: "australian terrier", label: "australian terrier"},
  {value: "german pinscher", label: "german pinscher"},
  {value: "black and tan coonhound", label: "black and tan coonhound"},
  {value: "norwich terrier", label: "norwich terrier"},
  {value: "cairn terrier", label: "cairn terrier"},
  {value: "soft coated wheaten terrier", label: "soft coated wheaten terrier"},
  {value: "pembroke welsh corgi", label: "pembroke welsh corgi"},
  {value: "english toy terrier", label: "english toy terrier"},
  {value: "great pyrenees", label: "great pyrenees"},
  {value: "alaskan husky", label: "alaskan husky"},
  {value: "thai ridgeback", label: "thai ridgeback"},
  {value: "shetland sheepdog", label: "shetland sheepdog"},
  {value: "irish terrier", label: "irish terrier"},
  {value: "appenzeller sennenhund", label: "appenzeller sennenhund"},
  {value: "toy fox terrier", label: "toy fox terrier"},
  {value: "tibetan spaniel", label: "tibetan spaniel"},
  {value: "american pit bull terrier", label: "american pit bull terrier"},
  {value: "lhasa apso", label: "lhasa apso"},
  {value: "boykin spaniel", label: "boykin spaniel"},
  {value: "standard schnauzer", label: "standard schnauzer"},
  {value: "miniature pinscher", label: "miniature pinscher"},
  {value: "miniature schnauzer", label: "miniature schnauzer"},
  {value: "yorkshire terrier", label: "yorkshire terrier"},
  {value: "border collie", label: "border collie"},
  {value: "west highland white terrier", label: "west highland white terrier"},
  {value: "samoyed", label: "samoyed"},
  {value: "american eskimo dog", label: "american eskimo dog"},
  {value: "bearded collie", label: "bearded collie"},
  {value: "smooth fox terrier", label: "smooth fox terrier"},
  {value: "bluetick coonhound", label: "bluetick coonhound"},
  {value: "shiba inu", label: "shiba inu"},
  {value: "english toy spaniel", label: "english toy spaniel"},
  {value: "australian cattle dog", label: "australian cattle dog"},
  {value: "cocker spaniel", label: "cocker spaniel"},
  {value: "great dane", label: "great dane"},
  {value: "coton de tulear", label: "coton de tulear"},
  {value: "tibetan terrier", label: "tibetan terrier"},
  {value: "old english sheepdog", label: "old english sheepdog"},
  {value: "affenpinscher", label: "affenpinscher"},
  {value: "pharaoh hound", label: "pharaoh hound"},
  {value: "scottish deerhound", label: "scottish deerhound"},
  {value: "cocker spaniel (american)", label: "cocker spaniel (american)"},
  {value: "welsh springer spaniel", label: "welsh springer spaniel"},
  {value: "rottweiler", label: "rottweiler"},
  {value: "australian kelpie", label: "australian kelpie"},
  {value: "chow chow", label: "chow chow"},
  {value: "american bulldog", label: "american bulldog"},
  {value: "treeing walker coonhound", label: "treeing walker coonhound"},
  {value: "vizsla", label: "vizsla"},
  {value: "chesapeake bay retriever", label: "chesapeake bay retriever"},
  {value: "belgian malinois", label: "belgian malinois"},
  {value: "siberian husky", label: "siberian husky"},
  {value: "saluki", label: "saluki"},
  {value: "whippet", label: "whippet"},
  {value: "kuvasz", label: "kuvasz"},
  {value: "cardigan welsh corgi", label: "cardigan welsh corgi"},
  {value: "maltese", label: "maltese"},
  {value: "irish setter", label: "irish setter"},
  {value: "rat terrier", label: "rat terrier"},
  {value: "scottish terrier", label: "scottish terrier"},
  {value: "border terrier", label: "border terrier"},
  {value: "komondor", label: "komondor"},
  {value: "bull terrier (miniature)", label: "bull terrier (miniature)"},
  {value: "pomeranian", label: "pomeranian"},
  {value: "alaskan malamute", label: "alaskan malamute"},
  {value: "clumber spaniel", label: "clumber spaniel"},
  {value: "schipperke", label: "schipperke"},
  {value: "redbone coonhound", label: "redbone coonhound"},
  {value: "bernese mountain dog", label: "bernese mountain dog"},
  {value: "rhodesian ridgeback", label: "rhodesian ridgeback"},
  {value: "basset hound", label: "basset hound"},
  {value: "greyhound", label: "greyhound"},
  {value: "wire fox terrier", label: "wire fox terrier"},
  {value: "cavalier king charles spaniel", label: "cavalier king charles spaniel"},
  {value: "english setter", label: "english setter"},
  {value: "alapaha blue blood bulldog", label: "alapaha blue blood bulldog"},
  {value: "papillon", label: "papillon"},
  {value: "irish wolfhound", label: "irish wolfhound"},
  {value: "french bulldog", label: "french bulldog"},
  {value: "golden retriever", label: "golden retriever"},
  {value: "bedlington terrier", label: "bedlington terrier"},
  {value: "nova scotia duck tolling retriever", label: "nova scotia duck tolling retriever"},
  {value: "airedale terrier", label: "airedale terrier"},
  {value: "german shorthaired pointer", label: "german shorthaired pointer"},
  {value: "boston terrier", label: "boston terrier"},
  {value: "newfoundland", label: "newfoundland"},
  {value: "italian greyhound", label: "italian greyhound"},
  {value: "giant schnauzer", label: "giant schnauzer"},
  {value: "american staffordshire terrier", label: "american staffordshire terrier"},
  {value: "american water spaniel", label: "american water spaniel"},
  {value: "afghan hound", label: "afghan hound"},
  {value: "weimaraner", label: "weimaraner"},
  {value: "silky terrier", label: "silky terrier"},
  {value: "labrador retriever", label: "labrador retriever"},
  {value: "dalmatian", label: "dalmatian"},
  {value: "glen of imaal terrier", label: "glen of imaal terrier"},
  {value: "basset bleu de gascogne", label: "basset bleu de gascogne"},
  {value: "gordon setter", label: "gordon setter"},
  {value: "akita", label: "akita"},
  {value: "basenji", label: "basenji"},
];
export { VALID_BREEDS };

const VALID_GROUPS = [
  {value: "Mixed", label: "Mixed"},
  {value: "Working", label: "Working"},
  {value: "Non-Sporting", label: "Non-Sporting"}, 
  {value: "Sporting", label: "Sporting"},
  {value: "Herding", label: "Herding"},
  {value: "Terrier", label: "Terrier"},
  {value: "Hound", label: "Hound"},
  {value: "Toy", label: "Toy"},
];
export { VALID_GROUPS };

const VALID_LIFESPANS = [
  {value: "6", label: "6"},
  {value: "7", label: "7"},
  {value: "8", label: "8"},
  {value: "9", label: "9"},
  {value: "10", label: "10"},
  {value: "11", label: "11"},
  {value: "12", label: "12"},
  {value: "13", label: "13"},
  {value: "14", label: "14"},
  {value: "15", label: "15"},
  {value: "16", label: "16"},
  {value: "17", label: "17"},
  {value: "18", label: "18"},
  {value: "19", label: "19"},
  {value: "20", label: "20"},
];
export { VALID_LIFESPANS };

const VALID_HEIGHTS = [
  {value: "8", label: "8"},
  {value: "9", label: "9"},
  {value: "10", label: "10"},
  {value: "11", label: "11"},
  {value: "12", label: "12"},
  {value: "13", label: "13"},
  {value: "14", label: "14"},
  {value: "15", label: "15"},
  {value: "16", label: "16"},
  {value: "17", label: "17"},
  {value: "18", label: "18"},
  {value: "19", label: "19"},
  {value: "20", label: "20"},
  {value: "21", label: "21"},
  {value: "22", label: "22"},
  {value: "23", label: "23"},
  {value: "24", label: "24"},
  {value: "25", label: "25"},
  {value: "26", label: "26"},
  {value: "27", label: "27"},
  {value: "28", label: "28"},
  {value: "29", label: "29"},
  {value: "30", label: "30"},
  {value: "31", label: "31"},
  {value: "32", label: "32"},
  {value: "33", label: "33"},
  {value: "34", label: "34"},
  {value: "35", label: "35"},
];
export { VALID_HEIGHTS };
