const VALID_CITIES = [
  {value: "Adkins", label: "Adkins"},
  {value: "Aledo", label: "Aledo"},
  {value: "Alvin", label: "Alvin"},
  {value: "Angleton", label: "Angleton"},
  {value: "Arlington", label: "Arlington"},
  {value: "Austin", label: "Austin"},
  {value: "Bandera", label: "Bandera"},
  {value: "Bastrop", label: "Bastrop"},
  {value: "Baytown", label: "Baytown"},
  {value: "Beeville", label: "Beeville"},
  {value: "Bellaire", label: "Bellaire"},
  {value: "Benbrook", label: "Benbrook"},
  {value: "Bergheim", label: "Bergheim"},
  {value: "Bertram", label: "Bertram"},
  {value: "Blanco", label: "Blanco"},
  {value: "Blessing", label: "Blessing"},
  {value: "Boerne", label: "Boerne"},
  {value: "Brenham", label: "Brenham"},
  {value: "Brownwood", label: "Brownwood"},
  {value: "Bryan", label: "Bryan"},
  {value: "Buchanan Dam", label: "Buchanan Dam"},
  {value: "Buda", label: "Buda"},
  {value: "Buffalo", label: "Buffalo"},
  {value: "Bulverde", label: "Bulverde"},
  {value: "Burleson", label: "Burleson"},
  {value: "Canyon Lake", label: "Canyon Lake"},
  {value: "Cat Spring", label: "Cat Spring"},
  {value: "Cedar Creek", label: "Cedar Creek"},
  {value: "Cedar Hill", label: "Cedar Hill"},
  {value: "Cedar Park", label: "Cedar Park"},
  {value: "Cleveland", label: "Cleveland"},
  {value: "Clifton", label: "Clifton"},
  {value: "Coldspring", label: "Coldspring"},
  {value: "Coleman", label: "Coleman"},
  {value: "College Station", label: "College Station"},
  {value: "Comanche", label: "Comanche"},
  {value: "Comfort", label: "Comfort"},
  {value: "Conroe", label: "Conroe"},
  {value: "Converse", label: "Converse"},
  {value: "Copperas Cove", label: "Copperas Cove"},
  {value: "Corpus Christi", label: "Corpus Christi"},
  {value: "Corsicana", label: "Corsicana"},
  {value: "Covington", label: "Covington"},
  {value: "Crowley", label: "Crowley"},
  {value: "Cuero", label: "Cuero"},
  {value: "Cypress", label: "Cypress"},
  {value: "Dallas", label: "Dallas"},
  {value: "Dickinson", label: "Dickinson"},
  {value: "Dripping Springs", label: "Dripping Springs"},
  {value: "Duncanville", label: "Duncanville"},
  {value: "Edna", label: "Edna"},
  {value: "El Campo", label: "El Campo"},
  {value: "Elgin", label: "Elgin"},
  {value: "Everman", label: "Everman"},
  {value: "Fischer", label: "Fischer"},
  {value: "Floresville", label: "Floresville"},
  {value: "Fort Worth", label: "Fort Worth"},
  {value: "Fredericksburg", label: "Fredericksburg"},
  {value: "Friendswood", label: "Friendswood"},
  {value: "Fulshear", label: "Fulshear"},
  {value: "Fulton", label: "Fulton"},
  {value: "Georgetown", label: "Georgetown"},
  {value: "Godley", label: "Godley"},
  {value: "Goliad", label: "Goliad"},
  {value: "Gonzales", label: "Gonzales"},
  {value: "Granbury", label: "Granbury"},
  {value: "Grand Prairie", label: "Grand Prairie"},
  {value: "Gun Barrel City", label: "Gun Barrel City"},
  {value: "Hearne", label: "Hearne"},
  {value: "Helotes", label: "Helotes"},
  {value: "Hempstead", label: "Hempstead"},
  {value: "Highlands", label: "Highlands"},
  {value: "Hillsboro", label: "Hillsboro"},
  {value: "Hitchcock", label: "Hitchcock"},
  {value: "Horseshoe Bay", label: "Horseshoe Bay"},
  {value: "Houston", label: "Houston"},
  {value: "Humble", label: "Humble"},
  {value: "Industry", label: "Industry"},
  {value: "Jarrell", label: "Jarrell"},
  {value: "Junction", label: "Junction"},
  {value: "Katy", label: "Katy"},
  {value: "Kendalia", label: "Kendalia"},
  {value: "Kenedy", label: "Kenedy"},
  {value: "Kennedale", label: "Kennedale"},
  {value: "Kerrville", label: "Kerrville"},
  {value: "Killeen", label: "Killeen"},
  {value: "Kingwood", label: "Kingwood"},
  {value: "Kyle", label: "Kyle"},
  {value: "La Vernia", label: "La Vernia"},
  {value: "Lago Vista", label: "Lago Vista"},
  {value: "Lake Jackson", label: "Lake Jackson"},
  {value: "Lakeway", label: "Lakeway"},
  {value: "Lampasas", label: "Lampasas"},
  {value: "Lancaster", label: "Lancaster"},
  {value: "League City", label: "League City"},
  {value: "Leander", label: "Leander"},
  {value: "Liberty Hill", label: "Liberty Hill"},
  {value: "Liverpool", label: "Liverpool"},
  {value: "Livingston", label: "Livingston"},
  {value: "Lockhart", label: "Lockhart"},
  {value: "Lott", label: "Lott"},
  {value: "Luling", label: "Luling"},
  {value: "Lytle", label: "Lytle"},
  {value: "Mabank", label: "Mabank"},
  {value: "Madisonville", label: "Madisonville"},
  {value: "Magnolia", label: "Magnolia"},
  {value: "Malakoff", label: "Malakoff"},
  {value: "Manchaca", label: "Manchaca"},
  {value: "Mansfield", label: "Mansfield"},
  {value: "Manvel", label: "Manvel"},
  {value: "Marble Falls", label: "Marble Falls"},
  {value: "Mason", label: "Mason"},
  {value: "Mexia", label: "Mexia"},
  {value: "Midlothian", label: "Midlothian"},
  {value: "Mingus", label: "Mingus"},
  {value: "Missouri City", label: "Missouri City"},
  {value: "Montgomery", label: "Montgomery"},
  {value: "Nassau Bay", label: "Nassau Bay"},
  {value: "Navasota", label: "Navasota"},
  {value: "New Braunfels", label: "New Braunfels"},
  {value: "Nixon", label: "Nixon"},
  {value: "Ovilla", label: "Ovilla"},
  {value: "Palacios", label: "Palacios"},
  {value: "Palestine", label: "Palestine"},
  {value: "Pasadena", label: "Pasadena"},
  {value: "Pearland", label: "Pearland"},
  {value: "Pearsall", label: "Pearsall"},
  {value: "Pflugerville", label: "Pflugerville"},
  {value: "Pipe Creek", label: "Pipe Creek"},
  {value: "Pleasanton", label: "Pleasanton"},
  {value: "Porter", label: "Porter"},
  {value: "Poteet", label: "Poteet"},
  {value: "Red Oak", label: "Red Oak"},
  {value: "Richmond", label: "Richmond"},
  {value: "Rockdale", label: "Rockdale"},
  {value: "Rosenberg", label: "Rosenberg"},
  {value: "Rosharon", label: "Rosharon"},
  {value: "Round Rock", label: "Round Rock"},
  {value: "San Antonio", label: "San Antonio"},
  {value: "San Leon", label: "San Leon"},
  {value: "San Marcos", label: "San Marcos"},
  {value: "Santa Fe", label: "Santa Fe"},
  {value: "Schertz", label: "Schertz"},
  {value: "Scurry", label: "Scurry"},
  {value: "Seabrook", label: "Seabrook"},
  {value: "Sealy", label: "Sealy"},
  {value: "Seguin", label: "Seguin"},
  {value: "Seven Points", label: "Seven Points"},
  {value: "Sheridan", label: "Sheridan"},
  {value: "Smithville", label: "Smithville"},
  {value: "Somerville", label: "Somerville"},
  {value: "South Houston ", label: "South Houston "},
  {value: "Spring", label: "Spring"},
  {value: "Stafford", label: "Stafford"},
  {value: "Stephenville", label: "Stephenville"},
  {value: "Sugar Land", label: "Sugar Land"},
  {value: "Taylor", label: "Taylor"},
  {value: "Temple", label: "Temple"},
  {value: "The Woodlands", label: "The Woodlands"},
  {value: "Thorndale", label: "Thorndale"},
  {value: "Tomball", label: "Tomball"},
  {value: "Universal City", label: "Universal City"},
  {value: "Uvalde", label: "Uvalde"},
  {value: "Van Vleck", label: "Van Vleck"},
  {value: "Venus", label: "Venus"},
  {value: "Victoria", label: "Victoria"},
  {value: "Von Ormy", label: "Von Ormy"},
  {value: "Waco", label: "Waco"},
  {value: "Waller", label: "Waller"},
  {value: "Wallis", label: "Wallis"},
  {value: "Waxahachie", label: "Waxahachie"},
  {value: "Weatherford", label: "Weatherford"},
  {value: "Webster", label: "Webster"},
  {value: "Wharton", label: "Wharton"},
  {value: "White Settlement", label: "White Settlement"},
  {value: "Whitney", label: "Whitney"},
  {value: "Wimberley", label: "Wimberley"},
  {value: "Windcrest", label: "Windcrest"},
];
export { VALID_CITIES };

const VALID_BREEDS = [
  {value: "norfolk terrier", label: "Norfolk Terrier"},
  {value: "doberman pinscher", label: "Doberman Pinscher"},
  {value: "boxer", label: "Boxer"},
  {value: "pug", label: "Pug"},
  {value: "bichon frise", label: "Bichon Frise"},
  {value: "bull terrier", label: "Bull Terrier"},
  {value: "briard", label: "Briard"},
  {value: "beagle", label: "Beagle"},
  {value: "tibetan mastiff", label: "Tibetan Mastiff"},
  {value: "shih tzu", label: "Shih Tzu"},
  {value: "field spaniel", label: "Field Spaniel"},
  {value: "keeshond", label: "Keeshond"},
  {value: "english springer spaniel", label: "English Springer Spaniel"},
  {value: "staffordshire bull terrier", label: "Staffordshire Bull Terrier"},
  {value: "australian terrier", label: "Australian Terrier"},
  {value: "german pinscher", label: "German Pinscher"},
  {value: "black and tan coonhound", label: "Black And Tan Coonhound"},
  {value: "norwich terrier", label: "Norwich Terrier"},
  {value: "cairn terrier", label: "Cairn Terrier"},
  {value: "soft coated wheaten terrier", label: "Soft Coated Wheaten Terrier"},
  {value: "pembroke welsh corgi", label: "Pembroke Welsh Corgi"},
  {value: "english toy terrier", label: "English Toy Terrier"},
  {value: "great pyrenees", label: "Great Pyrenees"},
  {value: "alaskan husky", label: "Alaskan Husky"},
  {value: "thai ridgeback", label: "Thai Ridgeback"},
  {value: "shetland sheepdog", label: "Shetland Sheepdog"},
  {value: "irish terrier", label: "Irish Terrier"},
  {value: "appenzeller sennenhund", label: "Appenzeller Sennenhund"},
  {value: "toy fox terrier", label: "Toy Fox Terrier"},
  {value: "tibetan spaniel", label: "Tibetan Spaniel"},
  {value: "american pit bull terrier", label: "American Pit Bull Terrier"},
  {value: "lhasa apso", label: "Lhasa Apso"},
  {value: "boykin spaniel", label: "Boykin Spaniel"},
  {value: "standard schnauzer", label: "Standard Schnauzer"},
  {value: "miniature pinscher", label: "Miniature Pinscher"},
  {value: "miniature schnauzer", label: "Miniature Schnauzer"},
  {value: "yorkshire terrier", label: "Yorkshire Terrier"},
  {value: "border collie", label: "Border Collie"},
  {value: "west highland white terrier", label: "West Highland White Terrier"},
  {value: "samoyed", label: "Samoyed"},
  {value: "american eskimo dog", label: "American Eskimo Dog"},
  {value: "bearded collie", label: "Bearded Collie"},
  {value: "smooth fox terrier", label: "Smooth Fox Terrier"},
  {value: "bluetick coonhound", label: "Bluetick Coonhound"},
  {value: "shiba inu", label: "Shiba Inu"},
  {value: "english toy spaniel", label: "English Toy Spaniel"},
  {value: "australian cattle dog", label: "Australian Cattle Dog"},
  {value: "cocker spaniel", label: "Cocker Spaniel"},
  {value: "great dane", label: "Great Dane"},
  {value: "coton de tulear", label: "Coton De Tulear"},
  {value: "tibetan terrier", label: "Tibetan Terrier"},
  {value: "old english sheepdog", label: "Old English Sheepdog"},
  {value: "affenpinscher", label: "Affenpinscher"},
  {value: "pharaoh hound", label: "Pharaoh Hound"},
  {value: "scottish deerhound", label: "Scottish Deerhound"},
  {value: "cocker spaniel (american)", label: "Cocker Spaniel (American)"},
  {value: "welsh springer spaniel", label: "Welsh Springer Spaniel"},
  {value: "rottweiler", label: "Rottweiler"},
  {value: "australian kelpie", label: "Australian Kelpie"},
  {value: "chow chow", label: "Chow Chow"},
  {value: "american bulldog", label: "American Bulldog"},
  {value: "treeing walker coonhound", label: "Treeing Walker Coonhound"},
  {value: "vizsla", label: "Vizsla"},
  {value: "chesapeake bay retriever", label: "Chesapeake Bay Retriever"},
  {value: "belgian malinois", label: "Belgian Malinois"},
  {value: "siberian husky", label: "Siberian Husky"},
  {value: "saluki", label: "Saluki"},
  {value: "whippet", label: "Whippet"},
  {value: "kuvasz", label: "Kuvasz"},
  {value: "cardigan welsh corgi", label: "Cardigan Welsh Corgi"},
  {value: "maltese", label: "Maltese"},
  {value: "irish setter", label: "Irish Setter"},
  {value: "rat terrier", label: "Rat Terrier"},
  {value: "scottish terrier", label: "Scottish Terrier"},
  {value: "border terrier", label: "Border Terrier"},
  {value: "komondor", label: "Komondor"},
  {value: "bull terrier (miniature)", label: "Bull Terrier (miniature)"},
  {value: "pomeranian", label: "Pomeranian"},
  {value: "alaskan malamute", label: "Alaskan Malamute"},
  {value: "clumber spaniel", label: "Clumber Spaniel"},
  {value: "schipperke", label: "Schipperke"},
  {value: "redbone coonhound", label: "Redbone Coonhound"},
  {value: "bernese mountain dog", label: "Bernese Mountain Dog"},
  {value: "rhodesian ridgeback", label: "Rhodesian Ridgeback"},
  {value: "basset hound", label: "Basset Hound"},
  {value: "greyhound", label: "Greyhound"},
  {value: "wire fox terrier", label: "Wire Fox Terrier"},
  {value: "cavalier king charles spaniel", label: "Cavalier King Charles Spaniel"},
  {value: "english setter", label: "English Setter"},
  {value: "alapaha blue blood bulldog", label: "Alapaha Blue Blood Bulldog"},
  {value: "papillon", label: "Papillon"},
  {value: "irish wolfhound", label: "Irish Wolfhound"},
  {value: "french bulldog", label: "French Bulldog"},
  {value: "golden retriever", label: "Golden Retriever"},
  {value: "bedlington terrier", label: "Bedlington Terrier"},
  {value: "nova scotia duck tolling retriever", label: "Nova Scotia Duck Tolling Retriever"},
  {value: "airedale terrier", label: "Airedale Terrier"},
  {value: "german shorthaired pointer", label: "German Shorthaired Pointer"},
  {value: "boston terrier", label: "Boston Terrier"},
  {value: "newfoundland", label: "Newfoundland"},
  {value: "italian greyhound", label: "Italian Greyhound"},
  {value: "giant schnauzer", label: "Giant Schnauzer"},
  {value: "american staffordshire terrier", label: "American Staffordshire Terrier"},
  {value: "american water spaniel", label: "American Water Spaniel"},
  {value: "afghan hound", label: "Afghan Hound"},
  {value: "weimaraner", label: "Weimaraner"},
  {value: "silky terrier", label: "Silky Terrier"},
  {value: "labrador retriever", label: "Labrador Retriever"},
  {value: "dalmatian", label: "Dalmatian"},
  {value: "glen of imaal terrier", label: "Glen Of Imaal Terrier"},
  {value: "basset bleu de gascogne", label: "Basset Bleu De Gascogne"},
  {value: "gordon setter", label: "Gordon Setter"},
  {value: "akita", label: "Akita"},
  {value: "basenji", label: "Basenji"},
];
export { VALID_BREEDS };

const VALID_GROUPS = [
  {value: "Mixed", label: "Mixed"},
  {value: "Working", label: "Working"},
  {value: "Non-Sporting", label: "Non-Sporting"}, 
  {value: "Sporting", label: "Sporting"},
  {value: "Herding", label: "Herding"},
  {value: "Terrier", label: "Terrier"},
  {value: "Hound", label: "Hound"},
  {value: "Toy", label: "Toy"},
];
export { VALID_GROUPS };

const VALID_LIFESPANS = [
  {value: "6", label: "6"},
  {value: "7", label: "7"},
  {value: "8", label: "8"},
  {value: "9", label: "9"},
  {value: "10", label: "10"},
  {value: "11", label: "11"},
  {value: "12", label: "12"},
  {value: "13", label: "13"},
  {value: "14", label: "14"},
  {value: "15", label: "15"},
  {value: "16", label: "16"},
  {value: "17", label: "17"},
  {value: "18", label: "18"},
  {value: "19", label: "19"},
  {value: "20", label: "20"},
];
export { VALID_LIFESPANS };

const VALID_HEIGHTS = [
  {value: "8", label: "8"},
  {value: "9", label: "9"},
  {value: "10", label: "10"},
  {value: "11", label: "11"},
  {value: "12", label: "12"},
  {value: "13", label: "13"},
  {value: "14", label: "14"},
  {value: "15", label: "15"},
  {value: "16", label: "16"},
  {value: "17", label: "17"},
  {value: "18", label: "18"},
  {value: "19", label: "19"},
  {value: "20", label: "20"},
  {value: "21", label: "21"},
  {value: "22", label: "22"},
  {value: "23", label: "23"},
  {value: "24", label: "24"},
  {value: "25", label: "25"},
  {value: "26", label: "26"},
  {value: "27", label: "27"},
  {value: "28", label: "28"},
  {value: "29", label: "29"},
  {value: "30", label: "30"},
  {value: "31", label: "31"},
  {value: "32", label: "32"},
  {value: "33", label: "33"},
  {value: "34", label: "34"},
  {value: "35", label: "35"},
];
export { VALID_HEIGHTS };
