"""empty message

Revision ID: d64020cb6abc
Revises: f50ee6985533
Create Date: 2019-03-19 15:59:43.171052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d64020cb6abc"
down_revision = "f50ee6985533"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "breed",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("group", sa.String(length=255), nullable=True),
        sa.Column("min_height", sa.Float(), nullable=True),
        sa.Column("max_height", sa.Float(), nullable=True),
        sa.Column("min_lifespan", sa.Float(), nullable=True),
        sa.Column("max_lifespan", sa.Float(), nullable=True),
        sa.Column("temperament", sa.String(length=1000), nullable=True),
        sa.Column("min_weight", sa.Float(), nullable=True),
        sa.Column("max_weight", sa.Float(), nullable=True),
        sa.Column("image_1", sa.String(length=1000), nullable=True),
        sa.Column("image_2", sa.String(length=1000), nullable=True),
        sa.Column("image_3", sa.String(length=1000), nullable=True),
        sa.Column("image_4", sa.String(length=1000), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("breed")
    # ### end Alembic commands ###
