"""empty message

Revision ID: e908552befdb
Revises: 5a4d2a39eece
Create Date: 2019-03-19 15:17:27.546102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e908552befdb"
down_revision = "5a4d2a39eece"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_free", sa.Boolean(), nullable=True),
        sa.Column("image1", sa.String(length=1000), nullable=True),
        sa.Column("image2", sa.String(length=1000), nullable=True),
        sa.Column("image3", sa.String(length=1000), nullable=True),
        sa.Column("image4", sa.String(length=1000), nullable=True),
        sa.Column("desgination", sa.String(length=255), nullable=True),
        sa.Column("weather", sa.Text(), nullable=True),
        sa.Column("directions", sa.Text(), nullable=True),
        sa.Column("date", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id", "type"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity")
    # ### end Alembic commands ###
